In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action = 'ignore')

In [25]:
df = pd.read_csv("dataset.csv")

In [26]:
df.drop("Unnamed: 0", axis = 1, inplace=True)

In [27]:
df

,User_ID,Personal,Theme,comment_day,Participant Type,Successful Submission Count,competition_enrollment_day,FeatureA,FeatureB,FeatureC,...,competition started hour,competition started minute,competition started second,User sign-in hour,User sign-in minute,User sign-in second,Time user completed action in hour,Time user completed action in minute,Time user completed action in second,Discussion Day
0,ID_000H9XOP_Month_5,-1.0,-1.0,0.0,0.0,0,0.0,-1,-1,-1.0,...,-1,-1,-1,15,18,11.439200,16.0,18.0,22.0,-1.0
1,ID_003YJHQA_Month_4,-1.0,-1.0,0.0,0.0,0,0.0,-1,-1,-1.0,...,-1,-1,-1,10,30,32.261855,11.0,31.0,30.0,-1.0
2,ID_004UKSJV_Month_1,-1.0,-1.0,0.0,0.0,0,0.0,-1,-1,-1.0,...,-1,-1,-1,-1,-1,-1.000000,9.0,17.0,9.0,-1.0
3,ID_004UKSJV_Month_12,-1.0,-1.0,0.0,0.0,0,0.0,-1,-1,-1.0,...,-1,-1,-1,8,32,14.997443,10.0,51.0,58.0,-1.0
4,ID_008D2J6C_Month_1,-1.0,-1.0,0.0,0.0,0,0.0,-1,-1,-1.0,...,-1,-1,-1,9,42,39.695313,10.0,44.0,55.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17386,ID_ZZMHNLNT_Month_4,-1.0,-1.0,0.0,0.0,0,0.0,-1,-1,-1.0,...,-1,-1,-1,10,55,11.435972,11.0,57.0,10.0,-1.0
17387,ID_ZZQK0LU6_Month_3,-1.0,-1.0,0.0,1.0,0,29.0,[2],[],28.0,...,9,0,0,9,48,48.866739,23.0,41.0,18.0,-1.0
17388,ID_ZZUNZJ2U_Month_2,-1.0,-1.0,0.0,0.0,0,0.0,-1,-1,-1.0,...,-1,-1,-1,22,15,18.135850,23.0,16.0,34.0,-1.0
17389,ID_ZZVM2KO7_Month_4,-1.0,-1.0,0.0,0.0,0,0.0,-1,-1,-1.0,...,-1,-1,-1,17,11,20.611646,NaN,NaN,NaN,-1.0
17390,ID_ZZVUJ45W_Month_3,-1.0,-1.0,0.0,1.0,0,5.0,[1],[7],4.0,...,6,0,0,8,24,33.732648,9.0,32.0,57.0,-1.0

In [28]:
df["Month"] = df["User_ID"].str[18:]
df["Month"] = pd.to_numeric(df["Month"])

In [29]:
df["Month"].unique()

array([ 5,  4,  1, 12,  2,  3, 11], dtype=int64)

In [37]:
df_train = df[(df["Month"]== 1) | (df["Month"]== 2) | (df["Month"]== 3) | (df["Month"]== 4) | (df["Month"]== 11) | (df["Month"]== 12)]

In [38]:
df_train["Month"].unique()

array([ 4,  1, 12,  2,  3, 11], dtype=int64)

In [39]:
df_train.shape

(14906, 53)

In [40]:
df_test = df[df["Month"]== 5]

In [41]:
df_test["Month"].unique()

array([5], dtype=int64)

In [42]:
df_test.shape

(2485, 53)

## CLUSTERING

In [44]:
from sklearn.cluster import KMeans

In [46]:
df_train.drop("User_ID", axis=1, inplace=True)

In [47]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14906 entries, 1 to 17390
Data columns (total 52 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Personal                              14906 non-null  float64
 1   Theme                                 14906 non-null  float64
 2   comment_day                           14906 non-null  float64
 3   Participant Type                      14906 non-null  float64
 4   Successful Submission Count           14906 non-null  int64
 5   competition_enrollment_day            14906 non-null  float64
 6   FeatureA                              14906 non-null  object
 7   FeatureB                              14906 non-null  object
 8   FeatureC                              14906 non-null  float64
 9   FeatureD                              14906 non-null  float64
 10  FeatureE                              14906 non-null  float64
 11  SecretCode                            14906 non-null  float64
 12  FeatureF                              4997 non-null   object
 13  FeatureG                              4997 non-null   object
 14  FeatureH                              14906 non-null  object
 15  FeatureI                              14906 non-null  float64
 16  competition_ended_year                14906 non-null  float64
 17  competition_ended_month               14906 non-null  float64
 18  competition_ended_day                 14906 non-null  float64
 19  competition_started_year              14906 non-null  float64
 20  competition_started_month             14906 non-null  float64
 21  competition_started_day               14906 non-null  float64
 22  Time user completed action            12940 non-null  object
 23  Day last active                       12940 non-null  float64
 24  count_UA                              14906 non-null  float64
 25  FeatureX                              14906 non-null  float64
 26  FeatureY                              14906 non-null  float64
 27  User sign-in month                    10408 non-null  float64
 28  User sign-in day                      14906 non-null  float64
 29  Discussion Hour                       14906 non-null  int64
 30  Discussion Minute                     14906 non-null  int64
 31  Discussion Second                     14906 non-null  float64
 32  Comment Hour                          14906 non-null  int64
 33  Comment Minute                        14906 non-null  int64
 34  Comment Second                        14906 non-null  float64
 35  competition enrollment hour           14906 non-null  int64
 36  competition enrollment minute         14906 non-null  int64
 37  competition enrollment second         14906 non-null  float64
 38  competition ended hour                14906 non-null  int64
 39  competition ended minute              14906 non-null  int64
 40  competition ended second              14906 non-null  int64
 41  competition started hour              14906 non-null  int64
 42  competition started minute            14906 non-null  int64
 43  competition started second            14906 non-null  int64
 44  User sign-in hour                     14906 non-null  int64
 45  User sign-in minute                   14906 non-null  int64
 46  User sign-in second                   14906 non-null  float64
 47  Time user completed action in hour    12940 non-null  float64
 48  Time user completed action in minute  12940 non-null  float64
 49  Time user completed action in second  12940 non-null  float64
 50  Discussion Day                        14906 non-null  float64
 51  Month                                 14906 non-null  int64
dtypes: float64(30), int64(16), object(6)
memory usage: 6.0+ MB

In [48]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2).fit(df_train)

ValueError: could not convert string to float: '[]'

In [53]:
kmeans = KMeans(init='k-means++', n_clusters=2, n_init=2)

In [ ]:
kmeans.fit(X)

In [ ]:
P = kmeans.predict(X)

In [ ]:
colors = list(map(lambda x: '#3b4cc0' if x == 1 else '#b40426', P))
plt.scatter(X[:,0], X[:,1], c=colors, marker="o", picker=True)
plt.title('Two clusters of data')
plt.xlabel('Temperature yesterday')
plt.ylabel('Temperature today')
plt.show()